### ISSUE TITLE
Bubbleupnpserver renderer

### ISSUE THREAD

**Issue by KeesKemper** [bazwilliams/openhomedevice#1]
The API is working fine with an openhome renderer created with openhome software. However it does not work when I try to access an openhome renderer created with Bubbleupn server. For instance I get the error: "AttributeError: 'NoneType' object has no attribute 'ControlUrl'" when I request the name of the device.

**Comment by cak85** [comment]
Hi,
I wanted to use this project, too, and had the same issue in combination with upmpdcli. Since @bazwilliams is not responding:
I have fixed this issue in 8f883e734bfee791ba9dfaa4c47d712ae91e3c91. See https://github.com/cak85/openhomedevice

Best regards,
Christian

**Comment by bazwilliams** [comment]
Hello!

Github never sent me an issue about this - just received a notification when you @cak85 tagged me. 

let me investigate.

**Comment by bazwilliams** [comment]
@cak85 Can you create a PR for your issue and I'll merge into this repo - again really sorry for not getting back!

**Comment by bazwilliams** [comment]
Version 0.2.2 has been published thanks to @cak85 sorry I missed this being opened!

**Comment by cak85** [comment]
You're welcome! I am not aware of how Github's notification system works; I am just using your great library and stumbled upon this bug.
