### ISSUE TITLE
play_media - feature request

### ISSUE THREAD

**Issue by printzlau** [bazwilliams/openhomedevice#6]
Would it be possible to implement a play_media control. This would be useful for tts in home-assistant.

**Comment by bazwilliams** [comment]
Good request and like the idea of TTS. 

Whilst straight forward to do, I'd need to consider what to do when other content is currently playing on the device - especially if you had a playlist in progress. 

I suspect using the 'radio' source may be the most appropriate so we don't mess with your playlist.
