### ISSUE TITLE
Play ?

### ISSUE THREAD

**Issue by arjunmenon** [bazwilliams/openhomedevice#7]
Hey
How do you set a song to play?
The TrackInfoParser does not set the song to play.
The `SetSource(index)` generally expects a integer. Bit unclear here, but How do you pass the song uri.
Also, can we use Upnp's `SetNextAVTransport` Uri for gapless playing?

Normally, is `openhomeDevice.Sources()` suppose to return nil, when you just setup?

**Comment by bazwilliams** [comment]
The `Play()` function doesn't take any arguments, it's a transport control, you need to have queued items on the device playlist in advance using a Upnp controller like Kazoo or BubbleDs. I've not added support for the playlist service. Here's the developer documentation for it: http://wiki.openhome.org/wiki/Av:Developer:PlaylistService

As far as `SetNextAVTransport` goes, it is not implemented as part of this library - feel free to submit a PR. The library is primarily targeted at Openhome or Linn devices using the PlaylistService or wanting information about what's playing.

**Comment by arjunmenon** [comment]
Okay. After trying out requests, we need to use `insert` and `seekid` for playing. 
Just to clarify, adding support for playlist service are you planning?

Also is there a way to set a room name through control point? I didn't see an action for that.

**Comment by bazwilliams** [comment]
I've no plans for the playlist service at this time, but wouldn't be too much work to use the transport service as a template.  

I think you set the product room using the product service.
